'use strict';
angular.module('waid.idm', [
  'waid.core',
  'waid.idm.controllers',
  'waid.idm.directives'
]).run(function (waidCore, waidCoreStrategy, waidCoreAppStrategy, waidService) {
  waidCore.config.setConfig('idm', {
    'templates': {
      'profile': '/templates/idm/profile.html',
      'overview': '/templates/idm/overview.html',
      'userProfileNavbar': '/templates/idm/user-profile-navbar.html',
      'userProfileStatusButton': '/templates/idm/user-profile-status-button.html',
      'termsAndConditionsModal': '/templates/idm/terms-and-conditions-modal.html',
      'completeProfileModal': '/templates/idm/complete-profile-modal.html',
      'linkSocialProfileModal': '/templates/idm/link-social-profile-modal.html',
      'lostLoginModal': '/templates/idm/lost-login-modal.html',
      'loginAndRegisterModal': '/templates/idm/login-and-register-modal.html',
      'userProfileModal': '/templates/idm/user-profile-modal.html',
      'loginAndRegisterHome': '/templates/idm/login-and-register-home.html',
      'socialLogin': '/templates/idm/social-login.html',
      'login': '/templates/idm/login.html',
      'register': '/templates/idm/register.html',
      'lostLogin': '/templates/idm/lost-login.html',
      'userProfileMenu': '/templates/idm/user-profile-menu.html',
      'userProfileHome': '/templates/idm/user-profile-home.html',
      'linkSocialProfile': '/templates/idm/link-social-profile.html',
      'associatedSocialAccounts': '/templates/idm/associated-social-accounts.html'
    },
    'translations': {
      'link_social_profile_intro': 'We hebben een bestaande account gevonden waarmee we de nieuwe social login willen koppelen. Ter beveiliging vragen we nogmaals je wachtwoord om deze koppeling af te ronden.',
      'link_social_profile_modal_title': 'Bestaande account koppelen aan nieuwe social account.',
      'link_social_profile_modal_close_button': 'Sluiten en niet koppelen',
      'link_social_profile_link_button': 'Doorgaan en social account koppelen',
      'auth-cancelled': 'Authenticatie is geannuleerd.',
      'auth-failed': 'Authenticatie is gefaald. Ons excuus voor het ongemak.',
      'auth-unknown-error': 'Een onbekende fout heeft zich voortgedaan. Ons excuus voor het ongemak.',
      'auth-missing-parameter': 'A needed parameter to continue the process was missing, usually raised by the services that need some POST data like myOpenID.',
      'auth-state-missing': 'The state parameter is missing from the server response.',
      'auth-state-forbidden': 'The state parameter returned by the server is not the one sent.',
      'auth-token-error': 'Geen permissie of toegang met de token. Kan hierdoor niet authenticeren. Controlleer de instellingen in de admin.',
      'auth-already-associated': 'Een andere gebruiker is al geassocieerd met de social account. Log uit en probeer nogmaals in te loggen met dezelfde social login.',
      'system-error': 'Systeem fout. Ons excuus voor het ongemak.',
      'edit': 'Wijzigen',
      'missing_profile_data': 'Om verder te gaan hebben we wat extra gegevens nodig...',
      'invalid_profile_data': 'Sommige profielgegevens zijn niet meer up-to-date of geldig meer. Pas deze gegevens aan om verder te gaan...',
      'email_is_not_verified': 'Er was al een e-mail naar je toe gestuurd met activatie link. Heb je deze niet ontvangen? voer opnieuw een geldig e-mailadres in en dan word er een nieuwe activatie e-mail gestuurd.',
      'delete':'Verwijderen',
      'male': 'Man',
      'female': 'Vrouw',
      'emails': 'E-mail adressen',
      'avatar': 'Profielfoto',
      'display_name': 'Profielnaam',
      'date_of_birth': 'Geboortedatum',
      'gender': 'Geslacht',
      'overview': 'Overzicht',
      'main': 'Algemeen',
      'telephone_numbers': 'Telefoon nummers',
      'telephone_number': 'Telefoon nummer',
      'edit_overview': 'Algemene gegevens aanpassen',
      'interests': 'Interesses',
      'like_tags': 'Wat vind je leuk?',
      'like_tags_help': 'Probeer in kernwoorden te antwoorden, bijvoorbeeld: vakantie, Bali, fietsen, muziek, auto\'s, Audi etc. We proberen interessante content met deze woorden voor je te selecteren.',
      'dislike_tags': 'Wat vind je echt niet leuk?',
      'edit_interests': 'Interesses aanpassen',
      'email_addresses': 'E-mail adressen',
      'edit_email_addresses': 'E-mail adressen aanpassen',
      'username': 'Gebruikersnaam',
      'edit_username': 'Gebruikersnaam wijzigen',
      'password': 'Wachtwoord',
      'password_confirm': 'Wachtwoord bevestiging',
      'edit_password': 'Wachtwoord wijzigen',
      'login_and_register_home_social_login_title': 'Log in met jouw Social account',
      'login_and_register_home_login_title': 'Inloggen',
      'login_and_register_home_register_title': 'Registreren',
      'login_and_register_home_social_login_intro': '<p>Maak gebruik van jouw social media account bij Facebook, Twitter of LinkedIn om snel en gemakkelijk in te loggen.</p>',
      'login_and_register_modal_close_button': 'Sluiten',
      'login_and_register_modal_title': 'Inloggen of registreren',
      'complete_profile_modal_title': 'Profiel update',
      'complete_profile_modal_close_button': 'Niet verdergaan en uitloggen',
      'login_lost_login_link': 'Login gegevens kwijt?',
      'login_submit': 'Inloggen',
      'login_form_password_label': 'Wachtwoord',
      'login_form_username_label': 'Gebruikersnaam',
      'lost_login_modal_title': 'Login gegevens kwijt?',
      'lost_login_modal_close_button': 'Sluiten',
      'lost_login_submit_button': 'Inlog gegevens ophalen',
      'lost_lostin_form_email': 'E-mailadres',
      'register_form_username': 'Gebruikersnaam',
      'register_form_email': 'E-mailadres',
      'register_form_password': 'Wachtwoord',
      'register_submit_register': 'Registreren',
      'register_submit_register_complete': 'Registratie afronden',
      'terms_and_conditions_check': 'Ik ga akkoord met de <a ng-click="waid.openTermsAndConditionsModal()">algemene voorwaarden</a>.',
      'terms_and_condition_modal_title': 'Algemene voorwaarden',
      'terms_and_condition_modal_close': 'Sluiten',
      'telephone_number_help': 'Voer hier een geldig nummer in het formaat : (landnummer) (netnummer/06) (telefoon)',
      'addresses': 'Adressen',
      'address': 'Adres',
      'city': 'Stad',
      'zipcode': 'Postcode',
      'country': 'Land',
      'about_public': 'Over mij',
      'about_public_help' : 'Publiekelijke informatie zichtbaar voor iedereen',
      'first_name':'Voornaam',
      'surname_prefix':'Tussenvoegsel',
      'surname':'Achternaam',
      'associated_social_accounts': 'Social koppelingen',
      'associated_social_accounts_intro': 'Met deze social koppelingen kan je snel inloggen op onze site. Klik op een van de social sites om te koppelen of te ontkoppelen.'
    }
  });
});